### ISSUE TITLE
Fix broken Travis due to changes in Ansible ("No module named json")

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa-ansible#83]
For a possible solution see: https://github.com/ansible/ansible/issues/61621

```
TASK [Create secrets] **********************************************************

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named json

fatal: [localhost -> 127.0.0.1]: FAILED! => changed=false 

  module_stderr: |-

    Traceback (most recent call last):

      File "/home/travis/.ansible/tmp/ansible-tmp-1574069964.2-143565745060280/AnsiballZ_vault_random.py", line 102, in <module>

        _ansiballz_main()

      File "/home/travis/.ansible/tmp/ansible-tmp-1574069964.2-143565745060280/AnsiballZ_vault_random.py", line 94, in _ansiballz_main

        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)

      File "/home/travis/.ansible/tmp/ansible-tmp-1574069964.2-143565745060280/AnsiballZ_vault_random.py", line 40, in invoke_module

        runpy.run_module(mod_name='ansible.modules.vault_random', init_globals=None, run_name='__main__', alter_sys=True)

      File "/usr/lib/python2.7/runpy.py", line 188, in run_module

        fname, loader, pkg_name)

      File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code

        mod_name, mod_fname, mod_loader, pkg_name)

      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code

        exec code in run_globals

      File "/tmp/ansible_vault_random_payload_EBOVLE/ansible_vault_random_payload.zip/ansible/modules/vault_random.py", line 14, in <module>

      File "/usr/lib/python2.7/dist-packages/ansible/cli/__init__.py", line 22, in <module>

        from ansible.inventory.manager import InventoryManager

      File "/usr/lib/python2.7/dist-packages/ansible/inventory/manager.py", line 38, in <module>

        from ansible.plugins.loader import inventory_loader

      File "/usr/lib/python2.7/dist-packages/ansible/plugins/loader.py", line 22, in <module>

        from ansible.parsing.utils.yaml import from_yaml

      File "/usr/lib/python2.7/dist-packages/ansible/parsing/utils/yaml.py", line 19, in <module>

        from ansible.parsing.ajson import AnsibleJSONDecoder

      File "/usr/lib/python2.7/dist-packages/ansible/parsing/ajson.py", line 11, in <module>

        from ansible.module_utils.common.json import AnsibleJSONEncoder

    ImportError: No module named json

  module_stdout: ''

  msg: |-

    MODULE FAILURE

    See stdout/stderr for the exact error

  rc: 1
```

**Comment by ulvida** [comment]
Same problem here, on a debian buster, with ansible 2.9 and virtualbox 6.1-

**Comment by racke** [comment]
Looks like I need to refactor the custom module :thinking:

**Comment by wakhan007** [comment]
I am getting the same above error while deploying sympa-anisble ( vbox6, ansible 2.9, vagrant 2.2).  Is there any solution to solve this?  Or could you please share any simple step-wise guide to deploy SYMPA.

**Comment by racke** [comment]
Repository is obsolete.
